[workspace]
name = "creator-payout-calculation"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]

[dependencies]
python = "3.11.*"
numpy = "1.26.*"
scipy = "1.11.*"
scikit-learn = "1.5.*"
pandas = "2.1.1.*"
matplotlib = "3.7.*"
seaborn = "0.12.*"
jupyterlab = "4.2.*"
psycopg2 = "2.9.*"
sqlalchemy = "2.0.*"
python-dotenv="1.2.*"
ipykernel = "7.1.*"
papermill = "2.6.*"
requests = "2.32.*"

[pypi-dependencies]
jupyterlab-vim = "*"
